### ISSUE TITLE
Graves not recoverable with /recovergrave

### ISSUE THREAD

**Issue by NinjaMandalorian** [Just1Developer/MC_BetterGraves#3]
Graves will not appear randomly, and not be recoverable with the command, using the exact co-ords given by the grave notification. I've also been told that if a grave dies ontop of an old grave, it overwrites it instead of placing it above.

**Comment by Just1Developer** [comment]
Hey NinjaMandalorian, that's scary!
I'll take a look at this as soon as possible, do you have a file of the grave that should be recoverable but isn't?
I have yet to get my hands on a corrupted / invalid grave file, so I can't really try and fix it.

**Comment by NinjaMandalorian** [comment]
Apologies, I tried to get them, unfortunately they were already deleted by someone else.

**Comment by Just1Developer** [comment]
No worries. I might have fixed it with 1.2.1, but if not, I'll get my hands on a file like that eventually.
Anyways, I made a new release that should hopefully resolve the issue.

[[GitHub]](https://github.com/Just1Developer/MC_BetterGraves/releases/tag/v1.2.1-release)
[[Spigot]](https://www.spigotmc.org/resources/bettergraves.111876/)
